spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_login
    username: root
    password: Hin7253a94

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    spring:
      security:
        oauth2:
          client:
            registration:


              github:
                client-id:
                client-secret:
                scope:
                  - read-user:
                  - user-email:

              linkedin:
               client-id:
               client-secret:
               authorization-grant-type:
               redirect-uri:
               scope:
                 - r_liteprofile:
                 - r_emailaddress:
               client-name: LinkedIn

               provider:
                 linkedin:
                   authorization-uri: https://www.linkedin.com/oauth/v2/authorization
                   token-uri: https://www.linkedin.com/oauth/v2/accessToken
                   user-info-uri: https://api.linkedin.com/v2/me
                   user-name-attribute: id

